Dam = {
    "Start": ["Chào cậu, tôi là Winer, một nhà nghiên cứu về lĩnh vực đa robot (multi-robot)"],
    "WhatisMultirobot": ["Chắc chắn! Lĩnh vực đa robot (multi-robot) là một phần quan trọng của robotics, nó nghiên cứu về cách nhiều robot có thể hợp tác và tương tác với nhau để hoàn thành các nhiệm vụ cụ thể",
                         "Trong thế giới thực, chúng ta không chỉ có một robot hoạt động một mình. Trong nhiều ứng dụng thực tế, có sự cần thiết phải có nhiều robot làm việc cùng nhau để tăng cường hiệu suất và linh hoạt",
                         "Điều này áp dụng cho nhiều lĩnh vực như dịch vụ hàng không, y tế, và sản xuất.",
                         "Lĩnh vực này đặt ra nhiều thách thức đầy thú vị, từ quản lý tài nguyên, đồng bộ hóa hành động, đến giải quyết xung đột giữa các robot",
                         " Điều này đồng thời mở ra nhiều cơ hội nghiên cứu để cải thiện hiệu suất và đưa ra những giải pháp sáng tạo trong thế giới robot hợp tác."],
    "FieldsofMultirobot": ["Để học về lĩnh vực đa robot, bạn cần chuẩn bị một sự hiểu biết cơ bản về lĩnh vực robotics và điều khiển tự động",
                           "Bạn có thể bắt đầu vơi một số lời gợi ý như:",
                           "Nắm vững các khái niệm cơ bản về robotics, lý thuyết điều khiển, và các thuật toán điều khiển robot.",
                           "Nắm vững một hoặc nhiều ngôn ngữ lập trình thích hợp cho robotics như Python, C++ hoặc MATLAB",
                           "Tìm hiểu về các công trình nghiên cứu và sách về lĩnh vực đa robot. Điều này sẽ giúp bạn hiểu rõ hơn về các ứng dụng, thuật toán và thách thức trong lĩnh vực này.",
                           "Tìm hiểu cách sử dụng các công cụ và phần mềm mô phỏng robot. Thực hành là cách tốt nhất để áp dụng kiến thức đã học.",
                           "Tham gia các cộng đồng trực tuyến hoặc nhóm nghiên cứu để kết nối với những người đang làm việc trong lĩnh vực này. Bạn có thể học được nhiều từ kinh nghiệm của họ."],
    "ChallengeforMe": ["Tôi đang bắt đầu phát triển một số hệ thống đa robot phối hợp cho mục đích quân sự, bạn có thể sẽ thích chơi với nó ",
                       "Đại loại thì các mô hình robot của tôi sẽ rất đông, hành động có quy luật và  chỉ tồn tại duy nhất 1 ý chí đó là huy diệt kẻ địch",
                       "Cậu cần sống lâu nhất có thể, chỉ vậy thôi, bạn có thể nhận được phần thưởng nếu sống qua vài phut.....",
                       "...."],
    "End": ["OK Tạm biệt cậu !"],
    "Option": {"WhatismultiR": 'Em có thể đặt câu hỏi "đa robot là gì không?"',
               "FieldsofMRobotics": "Làm thế nào để bắt đầu với lĩnh vực này và có khó khăn nào cần lưu ý không ạ",
               "ChallengeforMe": "Em nghe nói sẽ nhận được quà nếu hoàn thành một ài thử thách !!!",
               "End": "Tôi đi chỗ khác đây, làm việc vui vẻ !!!"}
}
Junie = {
    "Start": ["Chào cậu, đây là phòng thí nhiệm robotics RC, cậu cần tôi giúp gì không ?"],
    "WhatisControl": ["Lĩnh vực nghiên cứu của tôi xoay quanh lý thuyết điều khiển thông minh cho hệ thống robot. ",
                      'Về cơ bản thì tôi cố gắng hiểu cách cỗ máy hoạt động và tìm cách "hướng dẫn" chúng làm việc hay hoạt động "để có xu hướng thông minh hơn"',
                      'Điều này được thực hiện bằng rất nhiều, rất nhiều các công thức toán học và tối ưu hóa thú vị',
                      "À mà gần đây tôi có vài ý tưởng rất hay cho các hệ thống thông minh kiểu mới, nó nằm ngay ở căn phòng phía bắc...."],
    "FieldsofControl": ["Ah, câu hỏi hay đấy! Việc học về lý thuyết điều khiển không phải là dễ dàng, nhưng nó mang lại những thách thức thú vị",
                        " Lý thuyết này liên quan đến việc nghiên cứu về cách các hệ thống động cơ có thể được điều khiển một cách thông minh và hiệu quả.",
                        "Trong quá trình học, bạn sẽ tiếp xúc với các khái niệm phức tạp như điều khiển PID, các phương trình chuyển động, và các thuật toán học máy để cải thiện hiệu suất",
                        "Nhưng đừng lo, RClab sẽ là nơi tốt để bạn trao đổi và thực hành ",
                        "Nếu bạn có sự đam mê và sẵn sàng nỗ lực, thì lý thuyết điều khiển sẽ mở ra một cánh cửa cho bạn khám phá những khả năng mới trong lĩnh vực robot và tự động hóa."],
    "Howtocontrol": ["Chà ! Chúng ta sẽ cần hiểu biết 1 chút về toán học và vật lý, đây là nền tảng căn bản.",
                      "Ngoài ra thì hãy học lập trình, Python, Mathlab hoặc bất kỳ ngôn ngữ nào bạn nghĩ mình phù hợp ",
                      "Để chính thức bắt đầu thì bạn có thể xem một số tài liệu sách về điều khiển cơ bản như là PID Controllers, State Space Models và Control Systems Engineering",
                      "Và bạn có thể tham gia vào một phòng thí nhiệm chính thức để bắt đầu với những dự án đầu tiên"],
    "ChallengeforMe": ["Tôi sẽ giới thiệu cho bạn về một trò chơi nhỏ, nó lấy ý tưởng từ môt trong những mô hình kinh điển của giới điều khiển, mô hình con lắc ngược",
                       "Nó bao gồm một con lắc có thể giao động tự do được gắn vào một cơ cấu có thể dịch chuyển, mục tiêu của bài toán là tạo ra sự dịch chuyển chủ đông của cơ cấu phía dưới để giữ cho con lắc luôn có thể nằm ở vị trí thẳng đưứng",
                       "Khá dễ đúng không, tôi có thể dễ dàng dùng một hàm toán học để tự động hóa việc này, tuy nhiên sẽ khó hơn rất nhiều nếu làm nó một cách thủ công",
                       "Mô hình này là ý tưởng xuất phát ban đầu của nhiều thuật toán hiện đại, một trong số đó là các mô hình robot có chân."],
    "End": ["OK! Tạm biệt bạn !"],
    "Option": {"WhatisControl": "Cô nghiên cứu về lĩnh vực gì ở đây thế ạ",
               "FieldsofControl": "Lĩnh vực này có khó không ?",
               "Howtocontrol": "Làm sao để biết mình phù hợp và bắt đầu như thế nào với lĩnh vực của cô !?",
               "ChallengeforMe": "Cô có gì đó trực quan về lĩnh vực này hơn không ạ, để hiểu rõ tốt hơn ạ",
               "End": "Cảm ơn cô rất nhiều, em i đây !!!"}
}
Jon = {
    "Start": ["Chào cậu, cậu tìm tôi có việc gì không ?"],
    "WhatisRobotics": ["robot và robotics là hai khái niệm liên quan nhưng không giống nhau.",
                       " Robot là một thiết bị tự động có khả năng thực hiện công việc mà con người đã lập trình hoặc thiết kế cho nó.Trong khi đó, robotics là lĩnh vực nghiên cứu và phát triển các hệ thống tự động như robot.",
                       "Robotics không chỉ giới hạn ở việc tạo ra robot. Nó còn bao gồm nghiên cứu về cách chúng ta thiết kế, điều khiển và tương tác với các hệ thống tự động. Robotics kết hợp nhiều lĩnh vực như cơ khí, điện tử, máy tính, và trí tuệ nhân tạo."
                       ],
    "FieldsofRobotics": ["Robotics là lĩnh vực khá rộng lớn, nó là sự kết hợp của nhiều lĩnh vực khoa học khác nhau như khoa học máy tính, điện điện tử, cơ học toán và tối ưu hóa,....",
                         "Sẽ rât khó để ai đó có thể hiểu được tất cả những khối lĩnh vực liên quan đến robotics, nhưng bạn có thể bắt đầu một hướng nào đó của lĩnh vực theo nhiều cách khác nhau"
                         "Nó rất thú vị, hi vọng bạn có thể tham gia vào cộng đồng này cùng chúng tôi."],
    "IsItDifficult": ["Đúng là robotics có thể đầy thách thức, nhưng đồng thời nó cũng là một lĩnh vực rất đầy hứng thú. Việc học robotics đòi hỏi sự nỗ lực và kiên trì, nhưng nó mang lại những trải nghiệm độc đáo và đầy cảm hứng.",
                      "Trong quá trình học, bạn sẽ tiếp cận với nhiều kiến thức đa dạng từ lĩnh vực như điều khiển tự động, trí tuệ nhân tạo, cơ học, và nhiều hơn nữa. Điều này có thể đầy thách thức nhưng cũng làm tăng sự sáng tạo và khả năng giải quyết vấn đề của bạn.",
                      "Quan trọng nhất, hãy nhớ rằng mọi người đều bắt đầu từ điểm xuất phát. Nếu có lòng đam mê và sẵn sàng học hỏi, khó khăn sẽ trở thành cơ hội để phát triển."],
    "ChallengeforMe": ["Ồ thử thách à !!!",
                       "Bạn có biết là một trong những vẫn đề được chú ý rất nhiều của các mô hình robot di động là việc tạo ra quỹ đạo chuyển động tốt nhất cho chúng không ?",
                       "Bước đầu tiên và quan trọng nhât chính là xác định một tuyến đường từ vị trí bắt đàu đến vị trí két thúc",
                       "Tôi sẽ cho bạn một mê cung, hãy di chuển và tìm cách đi đến vị trí mục tieu nhanh nhất có thể",
                       "Nếu bạn có thể tìm được 1 quy tắc nào đó để luôn luôn xác định được đường đi đúng(một thuật toán so cool), bạn có thể trao đổi nó với người điều hướng thử thách để nhận một phần quà","Hi vọng bạn sẽ thích mê cung của tôi."],
    "End": ["OK Tạm biệt cậu !"],
    "Option": {"WhatisRobotics": "Robot và Robotics là gì ạ ?",
               "FieldsofRobotics": "Robotics có những lĩnh vực nào ạ",
               "IsItDifficult": "Robotics có khó không ?",
               "ChallengeforMe": "Em nghe nói mọi giáo sư trong phòng lab RC đều có một thử thách ẩn cho khách tham quan",
               "End": "Tôi đi chỗ khác đây, làm việc vui vẻ !!!"}
}
Content = {
    "Jon": Jon,
    "Dam": Dam,
    "Junie": Junie,
}
